_format_version: "3.0"
_transform: true

services:
  - name: auth-svc
    url: http://auth-svc:8000
    routes:
      - name: auth
        paths: ["/auth"]
        strip_path: false

  - name: employee-svc
    url: http://employee-svc:8000
    routes:
      - name: employee
        paths: ["/employee"]
        strip_path: false

  - name: attendance-svc
    url: http://attendance-svc:8000
    routes:
      - name: attendance
        paths: ["/attendance"]
        strip_path: false

  - name: leave-svc
    url: http://leave-svc:8000
    routes:
      - name: leave
        paths: ["/leave"]
        strip_path: false

  - name: agents-gateway
    url: http://agents-gateway:9003
    routes:
      - name: agents
        paths: ["/agents"]
        strip_path: false

plugins:
  - name: cors
    config:
      origins: ["*"]
      methods: ["GET","POST","PUT","DELETE","OPTIONS"]
      headers: ["Authorization","Content-Type"]
      credentials: true
      max_age: 3600

  - name: rate-limiting
    config:
      minute: 100
      policy: local

