_format_version: "3.0"
_transform: true

services:
  - name: auth-svc
    url: http://auth-svc:8000
    routes:
      - name: auth
        paths: ["/auth"]
        strip_path: false
  - name: employee-svc
    url: http://employee-svc:8000
    routes:
      - name: employee
        paths: ["/employee"]
        strip_path: false
  - name: agents-gateway
    url: http://agents-gateway:9003
    routes:
      - name: agents
        paths: ["/agents"]
        strip_path: false

plugins:
  - name: cors
    config:
      origins: ["*"]
      methods: ["GET","POST","PUT","DELETE","OPTIONS"]
      headers: ["Authorization","Content-Type"]
      credentials: true
      max_age: 3600
#
# Note:
# We keep Kong "thin" here (routing/CORS only). JWT validation happens inside the services
# via libs/py-hrms-auth::verify_bearer. If you want gateway-side OIDC, we can swap in the
# community 'kong-oidc' plugin with a custom Kong image in a follow-up PR.
