"""Initial employee tables

Revision ID: 0001
Revises: 
Create Date: 2024-01-01 00:00:00.000000

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '0001'
down_revision: Union[str, None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('employees',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('full_name', sa.String(length=200), nullable=False),
    sa.Column('email', sa.String(length=200), nullable=False),
    sa.Column('department', sa.String(length=100), nullable=False),
    sa.Column('position', sa.String(length=100), nullable=True),
    sa.Column('phone', sa.String(length=20), nullable=True),
    sa.Column('is_active', sa.Boolean(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index('ix_employees_active_created', 'employees', ['is_active', 'created_at'], unique=False)
    op.create_index('ix_employees_active_department', 'employees', ['is_active', 'department'], unique=False)
    op.create_index('ix_employees_department', 'employees', ['department'], unique=False)
    op.create_index('ix_employees_email', 'employees', ['email'], unique=True)
    op.create_index('ix_employees_full_name', 'employees', ['full_name'], unique=False)
    op.create_index('ix_employees_is_active', 'employees', ['is_active'], unique=False)
    op.create_index('ix_employees_search', 'employees', ['full_name', 'email'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index('ix_employees_search', table_name='employees')
    op.drop_index('ix_employees_is_active', table_name='employees')
    op.drop_index('ix_employees_full_name', table_name='employees')
    op.drop_index('ix_employees_email', table_name='employees')
    op.drop_index('ix_employees_department', table_name='employees')
    op.drop_index('ix_employees_active_department', table_name='employees')
    op.drop_index('ix_employees_active_created', table_name='employees')
    op.drop_table('employees')
    # ### end Alembic commands ###
